### ISSUE TITLE
Use Logary.Facade to avoid a dependency

### ISSUE THREAD

**Issue by haf** [wallymathieu/LogAdapter#3]
https://github.com/logary/logary/#using-logary-in-a-library

Since you have libraries for most things; use the facade there. Then in your composition root, the application runtime, reference Logary and replace the default targets with production worthy targets.

@wallymathieu: 
What needs to be done (in the README):
- List non dll dependency alternatives: Logary
- List logging interface alternatives: Logary, Microsoft.Extensions.Logging, and perhaps more

**Comment by wallymathieu** [comment]
The point of this library is to not take any dependency in c#. It looks like the complexity of the f# and c# facade projects look like they potentially create a conceptual dependency on logary. 

Since Microsoft has added `microsoft.extensions.logging` the point of the library seemed moot, however, since then I've noticed that that introduces breaking changes (in extensions logging) as well. Thus if Logary provides a more stable API surface that fullfill the same role, then we can deprecate these NuGet packages and point to Logary as an alternative (since that has more traction than this lib).

**Comment by haf** [comment]
What's a conceptual dependency?

**Comment by wallymathieu** [comment]
I meant that even though there is no dll dependency other logging libraries might not be able to implement the same contract. If you want us to repurpose LogAdapter NuGets for Logary, I'm quite OK with that (since I like if there are alternatives to for instance `microsoft.extensions.logging` that has some traction).

**Comment by wallymathieu** [comment]
There are very few downloads of the NuGet packages as well...

**Comment by wallymathieu** [comment]
The API surface that the facade presents suggests Logary, since many of the concepts look Logary related.

**Comment by wallymathieu** [comment]
The easiest thing to do here is to write something about the alternatives. So let's set that as the deliverable.
